name: label snyk PRs

# Start when a new PR is created from a snyk branch
on:
  pull_request:
    types: [ready_for_review, reopened, synchronize, opened]
  pull_request_review:
    types: [ submitted ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install_job:
    if: startsWith(github.head_ref, 'snyk-')
    name: install
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: test
        run: npm t

  auto_approve_job:
    needs: install_job
    runs-on: ubuntu-latest

    steps:
      - uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          method: squash
